// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwt3RFT_hbk-OIqMQP9I-LJpbCB2U1VYU',
    appId: '1:918791092406:web:b435fad98e41690ea3ce17',
    messagingSenderId: '918791092406',
    projectId: 'social-booster-fb131',
    authDomain: 'social-booster-fb131.firebaseapp.com',
    storageBucket: 'social-booster-fb131.appspot.com',
    measurementId: 'G-8QF6S61LQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-nlF49aFbdBh-cybUk-0Y_8ZUOBWGAKM',
    appId: '1:918791092406:android:32a6c8334779a5e0a3ce17',
    messagingSenderId: '918791092406',
    projectId: 'social-booster-fb131',
    storageBucket: 'social-booster-fb131.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgnVOzXt4s1nrYFvekTLNcxmsASSgkToo',
    appId: '1:918791092406:ios:e080605f1301e63aa3ce17',
    messagingSenderId: '918791092406',
    projectId: 'social-booster-fb131',
    storageBucket: 'social-booster-fb131.appspot.com',
    iosBundleId: 'com.example.socialBoster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgnVOzXt4s1nrYFvekTLNcxmsASSgkToo',
    appId: '1:918791092406:ios:c425c9b953d0dd9ba3ce17',
    messagingSenderId: '918791092406',
    projectId: 'social-booster-fb131',
    storageBucket: 'social-booster-fb131.appspot.com',
    iosBundleId: 'com.example.socialBoster.RunnerTests',
  );
}
